---
- name : get ant
  command : 'wget -O /tmp/ant.tar.bz2 {{ ant_url }}'
  register: ant_download

- name: Install Ant
  unarchive: src=/tmp/ant.tar.bz2 dest=/usr copy=no
  register: ant_installed
  when: ant_download|changed

- name: get ant-version
  shell: tar jtf /tmp/ant.tar.bz2 | head -1 | awk -F"/" '{print $1}'
  register: ant_version
  when: ant_download|changed

- name: Create symlink
  file: src=/usr/{{ item }} dest=/usr/ant  state=link
  when: ant_version|changed
  with_items: ant_version.stdout_lines


- name: Update profile Ant
  copy: src=ant.sh dest=/etc/profile.d/ant.sh
