---
- name : get maven
  command : 'wget -O /tmp/maven.tar.gz {{ maven_url }}'
  register: maven_download

- name: Install maven
  unarchive: src=/tmp/maven.tar.gz dest=/usr copy=no
  register: maven_installed
  when: maven_download|changed

- name: get maven-version
  shell: tar ztvf /tmp/maven.tar.gz | head -1 | awk -F"/" '{print $1}'
  register: maven_installed
  when: maven_download|changed


- name: Create symlink
  file: src=/usr/{{ item }} dest=/usr/maven  state=link
  when: maven_version|changed
  with_items: maven_version.stdout_lines

- name: Update profile Ant
  copy: src=maven.sh dest=/etc/profile.d/maven.sh
